name: Create release branch

on:
  workflow_dispatch:

jobs:
  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MOBILE_GITHUB_PAT }}
      - name: Initialize mandatory git config
        env:
          GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
          GITOPS_USER: ${{ secrets.GITOPS_USER }}
          GITOPS_USER_EMAIL: ${{ secrets.GITOPS_USER_EMAIL }}
        run: |
          git config user.name "$GITOPS_USER"
          git config user.email "$GITOPS_USER_EMAIL"

      - name: Extract version from Deps.kt
        run: |
          VERSION=$(grep appSourceVersionName build.gradle | awk -F \" '{print $2}')
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.RELEASE_VERSION }}
          version-fragment: 'feature'

      - name: Create release branch and bump build.gradle
        run: |
          git checkout -b release/${{ steps.bump_version.outputs.next-version }}
          sed -i 's/appSourceVersionName = "${{ env.RELEASE_VERSION }}"/appSourceVersionName = "${{ steps.bump_version.outputs.next-version }}"/g' build.gradle
          old_version_code=$(grep appSourceVersionName build.gradle | grep -o "[0-9]\+")
          new_version_code="$(($old_version_code + 1))"
          sed -i "s/appSourceVersionName = ${old_version_code}/appSourceVersionName = ${new_version_code}/g" build.gradle
          git add build.gradle
          git commit --message "Prepare release ${{ steps.bump_version.outputs.next-version }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push new branch
        run: git push origin release/${{ steps.bump_version.outputs.next-version }}

      - name: Create pull request
        uses: thomaseizinger/create-pull-request@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: release/${{ steps.bump_version.outputs.next-version }}
          base: master
          title: Release version ${{ steps.bump_version.outputs.next-version }}
          reviewers: ${{ github.actor }}
          body: |
            Hi @${{ github.actor }}!
            This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
            I've updated the bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.
            Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.
